name: Build scanservjs-hplip

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Run every day at noon UTC
  repository_dispatch:
    types: [new-release]

env:
  DOCKER_HUB_IMAGE_NAME: scanservjs-hplip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        run: git clone https://github.com/sbs20/scanservjs.git source

      - name: Get latest release tag
        run: |
          cd source
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Build Docker image (scanservjs-hplip)
        run: |
          cd source
          docker build --target scanservjs-hplip -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_IMAGE_NAME }}:$LATEST_TAG .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_IMAGE_NAME }}:$LATEST_TAG
